Create mage-training-arena-telekinetic-puzzle
jamiegyoung/runemarkers pull request #339
Opened 2024-10-01 00:36 UTC by swirle13

Create tiles for the Mage Training Arena for the Telekinetic puzzle room. The tiles are a refinement of the most efficient tile position to cast telegrab to save as many seconds on this horrible grind.

The tiles maximize the amount of tiles moved while the maze guardian is sliding, meaning that movement is prioritized only when unable to cast the next telegrab on the guardian. They also minimize the amount of time standing and waiting for the guardian to stop moving.

This is an improvement over the modest attempt for the tiles included in the MTA plugin when I spent time optimizing the puzzles to remove much of the inefficient standing around.

2024-10-03 01:52 UTC, jamiegyoung commented
Thanks for the tiles! I'll check them out and merge if it all looks good :+1:

2024-10-03 02:05 UTC, jamiegyoung requested changes
Couple of small things:
- The file created is not a `.json` file and therefore is not generating a page, I don't mind fixing this as it's just a small change
- There is no source for these tiles, if you made them yourself then feel free to either link your github or put your rsn, I don't mind. I just like to keep track of where things come from and credit those who deserve it (which you do).
- If you have a video guide for these tiles it would be extremely useful, not going to block it if you don't so don't worry.

Again, thanks for the tiles!

2024-10-30 05:09 UTC, swirle13 commented
Hey Jamie, yeah, I just created these myself, no video or anything, just a lot of telekinetic puzzle grinding had me create these. I'll try to get this updated in the next few days

2024-12-19 11:57 UTC, jamiegyoung commented
Any update on this?

2025-02-21 19:01 UTC, jamiegyoung commented
Closing this for now as there's not been any activity on it in a while

2025-02-21 19:01 UTC, closed without merging

2025-03-12 03:26 UTC, swirle13 commented
@jamiegyoung I added the same tile markers to the tilemarkers plugin for runelite, so I had stalled on this implementation. I figure with them added into the runelite client itself via plugin, it's more native for users than with your site.

I did quit playing osrs back in December, so I've unfortunately left a few contributing projects in the middle of progress.